MeiyuTech/AET-App

src/app/(frontend)/(aet-app)/components/Checkout/SuccessMessage.tsx
- Remove unnecessary state management and page refresh logic
- Update payment status text from 'Loading...' to 'Processing...'
- Remove unused imports and state hooks
- Streamline component rendering
=> refactor: Simplify SuccessMessage component

src/app/(frontend)/(aet-app)/components/Checkout/SuccessMessage.tsx
- Include console logs for application data, ID, payment details
- Create local paidAt variable for consistent date formatting
- Simplify date rendering logic in payment timestamp display
=> feat: Add debug logging to SuccessMessage component

src/app/(frontend)/(aet-app)/components/Checkout/SuccessMessage.tsx
- Remove redundant commented-out payment timestamp section
- Simplify component by eliminating unused code block
=> refactor: Remove commented-out paid timestamp in SuccessMessage

src/app/(frontend)/(aet-app)/components/Checkout/SuccessMessage.tsx
- Move date localization before component return to prevent hydration errors
- Uncomment paid timestamp section with updated rendering logic
- Add comment explaining hydration prevention strategy
=> fix: Resolve hydration issue in SuccessMessage component

src/app/(frontend)/(aet-app)/checkout/success/page.tsx
- Use specific locale formatting for paid timestamp
- Add comprehensive date and time formatting options
- Ensure consistent timestamp representation on server-side
=> fix: Enhance paid timestamp formatting with detailed locale options

src/app/(frontend)/(aet-app)/checkout/success/page.tsx, src/app/(frontend)/(aet-app)/components/Checkout/SuccessMessage.tsx
- Remove console logs from SuccessMessage component
- Simplify SuccessPage by removing server-side timestamp formatting
- Streamline data passing between server and client components
=> fix: Remove debug logging and server-side timestamp formatting

src/app/(frontend)/(aet-app)/checkout/success/page.tsx
- Wrap SuccessMessage component in a div with padding
- Improve visual spacing on the checkout success page
=> fix: Add padding to SuccessPage checkout success container

src/app/(frontend)/(aet-app)/components/Checkout/SuccessMessage.tsx, src/app/(frontend)/(aet-app)/components/applications-table.tsx, src/app/(frontend)/(aet-app)/utils/dateFormat.ts
- Create new dateFormat utility function to centralize timestamp formatting
- Refactor ApplicationsTable and SuccessMessage to use new formatDateTime function
- Improve code reusability and maintain consistent date formatting across components
=> fix: Extract date formatting utility for consistent timestamp display

src/app/(frontend)/(aet-app)/components/CheckoutForm.tsx, src/app/(frontend)/(aet-app)/utils/stripe/config.client.ts
- Create new config.client.ts for environment-specific Stripe publishable key
- Refactor CheckoutForm to use centralized Stripe key configuration
- Implement dynamic key selection based on NODE_ENV
=> feat: Add client-side Stripe configuration module

src/app/(frontend)/(aet-app)/components/Footer.tsx
- Replace generic office locations with Irvine, CA address
- Update phone number to (949) 954-7996
- Change email to ca2@aet21.com
- Add WeChat contact information
- Improve contact details formatting and readability
=> feat: Update Footer with precise contact information for AET

src/app/(frontend)/(aet-app)/api/stripe/webhook/route.ts
- Simplified the handling of client_reference_id in the Stripe webhook by assigning it to a variable for better readability and consistency. This change ensures that the application correctly references the client ID across various session events, improving the robustness of the webhook processing.
=> fix: Refactor client_reference_id handling in Stripe webhook

src/app/(frontend)/(aet-app)/api/stripe/create-payment-link/route.ts, src/app/(frontend)/(aet-app)/components/ApplicationsTable/PaymentLinkDialog.tsx
- Enhanced the payment link creation API to support additional payment methods including Alipay and US bank accounts.
- Improved error messaging in the PaymentLinkDialog to provide clearer guidance on invalid payment amounts or application IDs.
=> feat: Update payment link creation parameters and error messaging

emails/components/CheckoutSummaryCard.tsx, src/app/(frontend)/(aet-app)/components/StatusCheck/SelectedServicesCard.tsx
- Introduced a new CheckoutSummaryCard component to display detailed summaries of selected services in emails.
- Enhanced SelectedServicesEmailCard and SelectedServicesCard components to dynamically calculate and display service prices based on selected options.
- Updated pricing logic for foreign credential evaluations and course-by-course evaluations to ensure accurate cost representation.
- Improved overall structure and readability of service summaries in email templates.
=> feat: Add CheckoutSummaryCard component for email summaries

src/app/(frontend)/(aet-app)/components/ApplicationsTable/FilesDialog.tsx
- Modified the full name construction logic to include middle names if present, ensuring a more complete representation of the application user's name.
- Added a fallback to 'Not provided' if no name components are available, enhancing user experience and data handling.
=> fix: Update full name construction in FilesDialog component

src/app/(frontend)/(aet-app)/api/stripe/webhook/route.ts, src/app/(frontend)/(aet-app)/components/Email/templates/PaymentConfirmation/PaymentConfirmationEmail.tsx, src/app/(frontend)/(aet-app)/components/FCEApplicationForm/utils.ts
- Reimplemented the payment confirmation email logic in the Stripe webhook route, ensuring proper error handling for missing session amounts.
- Updated the PaymentConfirmationEmail component to format payment and completion dates using the EST timezone for consistency.
- Enhanced the getEstimatedCompletionDate utility to calculate estimated completion dates based on service types and payment timing, including business day considerations.
=> feat: Enhance payment confirmation email functionality and date handling

src/app/(frontend)/(aet-app)/api/stripe/webhook/route.ts, src/app/(frontend)/(aet-app)/components/Email/templates/PaymentConfirmation/PaymentConfirmationEmail.tsx, src/app/(frontend)/(aet-app)/utils/email/actions.tsx
- Modified the Stripe webhook route to pass the payment date to the payment confirmation email component.
- Updated the PaymentConfirmationEmail component to utilize the passed payment date for formatting, ensuring accurate display of payment information.
- Adjusted utility functions to accommodate the new payment date parameter for improved email content generation.
=> fix: Update payment confirmation email to include payment date

src/app/(frontend)/(aet-app)/api/supabase/check-expired/route.ts
- Implemented API key validation in the production environment to secure access to the check-expired API.
- Added logging for unauthorized access attempts to improve monitoring and security.
- Updated comments for clarity regarding authorization checks.
=> feat: Enhance API security for check-expired route

src/app/(frontend)/(aet-app)/components/ApplicationsTable/columns.tsx
- Introduced a tooltip for the delivery method in the ApplicationsTable, indicating when physical delivery is required.
- Enhanced the button layout for better visual organization and user interaction.
- Integrated the Truck icon from lucide-react to represent delivery needs, improving the UI experience.
=> feat: Add delivery method tooltip to ApplicationsTable component

src/app/(payload)/admin/CRM/degree-equivalency-tool/page.tsx, src/app/(payload)/admin/CRM/page.tsx
- Introduced a new button in the CRM page for accessing the Degree Equivalency AI Tester, improving navigation.
- Refined the layout of the Degree Equivalency AI Tester component, enhancing the user interface with better organization and spacing.
- Utilized @Shadcn/ui components to maintain design consistency and improve user experience.
=> feat: Add Degree Equivalency AI Tester button and enhance layout

src/app/(frontend)/(aet-app)/api/stripe/webhook/route.ts
- Enhanced the Stripe webhook route to check for existing payment records before insertion, allowing for updates to existing records or creation of new ones as needed.
- Improved error handling for payment record retrieval, ensuring robust logging and response management.
- Utilized randomUUID for generating unique IDs for new payment records, maintaining data integrity.
=> feat: Improve payment record handling in Stripe webhook

src/app/(frontend)/(aet-app)/api/stripe/webhook/route.ts
- Updated the Stripe webhook route to improve handling of degree equivalency payments, ensuring no delivery time or email notifications are required.
- Enhanced logging for same-day service calculations and payment confirmation email processes, improving traceability and debugging.
- Maintained existing error handling for payment confirmation email failures, ensuring robust response management.
=> fix: Refine Stripe webhook handling for payment processing

src/app/(frontend)/(aet-app)/components/DegreeEquivalencyForm/services/vision.service.ts
- Commented out console logs for the decoded Google Cloud private key to enhance security and reduce unnecessary output during runtime.
- Maintained the functionality of the VisionService while improving code cleanliness and focus on essential operations.
=> chore: Remove debug logging from VisionService
